### ISSUE TITLE
Why have two dimension resources file ?

### ISSUE THREAD

**Issue by amy6** [UdacityAndroidBasicsScholarship/udacity-forums#36]
I see two dimension resource files - `dimens.xml` and `dimention.xml` . Is there any specific reason for having two ?
``<dimen name="fontSize_20">20sp</dimen>`` exists in both the files and hence getting a build error.

**Comment by lucifer0987** [comment]
yeah, I have removed it, and now, you won't get any error... 
But sync your forked repo from random-changes branch.. we haven't updated the master branch yet.
After testing it, you can share the experience here... what improvements does it need?
